version: "3.9"

services:
  db:
    image: postgres:16
    container_name: test_order_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: test_order_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://admin:secret@db:5432/mydb
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"

volumes:
  pgdata:
